name: Wine Ubuntu CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          sudo curl --create-dirs -o /usr/include/linux/ntsync.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/6.12/main/include/uapi/linux/ntsync.h
          cd wine-tkg-git 
          sed -i 's/ntsync="false"/ntsync="true"/' customization.cfg
          sed -i 's/esync="true"/esync="false"/' customization.cfg
          sed -i 's/fsync="true"/fsync="false"/' customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
