name: Wine Fedora CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dnf -y -q upgrade --refresh
          # ntsync.h from kernel-headers may be broken, overwrite it ourselves
          sudo dnf -y install kernel-headers
          sudo curl -o /usr/include/linux/ntsync.h https://raw.githubusercontent.com/torvalds/linux/13845bdc869f136f92ad3d40ea09b867bb4ce467/include/uapi/linux/ntsync.h
          cd wine-tkg-git 
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
